In [34]:
import torch
from torch import nn


# 为了方便起见，我们定义了一个计算卷积层的函数。
# 此函数初始化卷积层权重，并对输入和输出提高和缩减相应的维数
def comp_conv2d(conv2d, X):
    # 这里的（1，1）表示批量大小和通道数都是1
    X = X.reshape((1, 1) + X.shape)
    Y = conv2d(X)
    # 省略前两个维度：批量大小和通道
    return Y.reshape(Y.shape[2:])

# 请注意，这里每边都填充了1行或1列，因此总共添加了2行2列
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1)
X = torch.rand(size=(8, 8))
print(X)
comp_conv2d(conv2d, X).shape

tensor([[0.0900, 0.7466, 0.4205, 0.0104, 0.7920, 0.4925, 0.9136, 0.1504],
        [0.0600, 0.1687, 0.8701, 0.1691, 0.6440, 0.3367, 0.5380, 0.4808],
        [0.4188, 0.2135, 0.3427, 0.4727, 0.2225, 0.2387, 0.3907, 0.7822],
        [0.5499, 0.3242, 0.7770, 0.2228, 0.7771, 0.4207, 0.4911, 0.7253],
        [0.3305, 0.8125, 0.0960, 0.9520, 0.5767, 0.7025, 0.9067, 0.1115],
        [0.0372, 0.6310, 0.5562, 0.3715, 0.0631, 0.4662, 0.4622, 0.9200],
        [0.1807, 0.2145, 0.9386, 0.8383, 0.5459, 0.4457, 0.9247, 0.4124],
        [0.8553, 0.2396, 0.8809, 0.1254, 0.3160, 0.4241, 0.8425, 0.3405]])


torch.Size([8, 8])

In [35]:
conv2d = nn.Conv2d(1, 1, kernel_size=(5, 3), padding=(2, 1))
comp_conv2d(conv2d, X).shape

torch.Size([8, 8])

In [36]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)
comp_conv2d(conv2d, X).shape

torch.Size([4, 4])

In [37]:
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
comp_conv2d(conv2d, X).shape

torch.Size([2, 2])

In [38]:
import torch
from d2l import torch as d2l

def corr2d_multi_in(X, K):
    # 先遍历“X”和“K”的第0个维度（通道维度），再把它们加在一起
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K))

In [39]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [49]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    # 全连接层中的矩阵乘法
    Y = torch.matmul(K, X)
    print(Y.shape)
    return Y.reshape((c_o, h, w))

In [50]:
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)

print(Y1)

torch.Size([2, 9])
tensor([[[ 0.2333, -1.0775,  0.3279],
         [ 0.9340,  1.6338,  0.3021],
         [ 0.8872, -0.5905,  0.2312]],

        [[ 0.3451,  0.0352,  0.9788],
         [ 0.7858,  0.2550,  1.8664],
         [-0.3289, -0.8498, -2.2041]]])
